### ISSUE TITLE
`branch create` wipes staged changes if branch already exists

### ISSUE THREAD

**Issue by codygibb** [abhinav/git-spice#307]
Repro steps:

Create a branch:
```
$ git checkout -B codyg/test
```

Go back to master, make some changes, and stage them:
```
$ git checkout master
$ echo "some change" > change.txt
$ git add change.txt
```
Attempt to create a branch with the staged changes, but use a branch name that already exists (i.e. the one we just created):
```
$ gs branch create codyg/test
[detached HEAD 5b508d8dd17] some change
 1 file changed, 1 insertion(+)
 create mode 100644 change.txt
FTL gs: create branch: git branch: exit status 128
```
This boots us back on master, but wipes the staged changes:
```
$ gst
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ cat change.txt
cat: change.txt: No such file or directory
```
Note, the change is still available in the detached HEAD commit:
```
$ git checkout 5b508d8dd17
$ cat change.txt
some change
```

**Comment by abhinav** [comment]
Yeah, that's an oversight.
There are two things missing here:

- branch create should probably check if branch exists in advance and reject the rest. (Will probably need a `--force` flag similarly to `git branch -f`).
- branch create has existing logic for "if anything goes wrong, go back to previous commit," but that will still lose the commit. The command either needs to restore the old state of index and working tree, or at least one of those, so that the user can recover.
