### ISSUE TITLE
Use `git-spice` on multiple machine to update the same stack

### ISSUE THREAD

**Issue by messense** [abhinav/git-spice#325]
Currently it seems that when I do `gs branch track` and `gs stack submit` on multiple machine to manage the same stack, it will post duplicate stack navigation comments in PR.

**Comment by abhinav** [comment]
Thanks for the report! Yeah, this is annoying, but fortunately fixable.

We'll probably want to post a marker comment like (maybe `<!-- gs:navigation comment -->`),
and then in `stack submit` where [we match against existing PRs](https://github.com/abhinav/git-spice/blob/43e2e7d30ee7eddcc4345b9472dd393f759d9be9/branch_submit.go#L210),
we'll need to also look for comments on the PR with that text.
This needs 

Related: I expect #289 to be done soon-ish, so that flag for that optoin would provide a short-term workaround to this.
