### ISSUE TITLE
Add `--no-verify` to commit, push, etc

### ISSUE THREAD

**Issue by ElPicador** [abhinav/git-spice#380]
I'm using a lot of pre-commit/push hooks. And sometimes skipping them with a `--no-verify` can be useful.

I'm willing to implement this feature. Is it something you would be open to accept as a contribution? Any tips/comments on how to implement it?

**Comment by abhinav** [comment]
Hello! Yes, a contribution for this would be welcome.

In terms of implementation:
The flag will be added to [branchCreateCmd](https://github.com/abhinav/git-spice/blob/8cc330f5fa24bfbc80fb61d8fab0c03716927eb9/branch_create.go#L14) and the three commit subcommands [amend](https://github.com/abhinav/git-spice/blob/8cc330f5fa24bfbc80fb61d8fab0c03716927eb9/commit_amend.go#L13), [create](https://github.com/abhinav/git-spice/blob/8cc330f5fa24bfbc80fb61d8fab0c03716927eb9/commit_create.go#L13), and [split](https://github.com/abhinav/git-spice/blob/8cc330f5fa24bfbc80fb61d8fab0c03716927eb9/commit_split.go#L13). All of these commands call `git.Repository.Commit`, which accepts a [git.CommitRequest](https://github.com/abhinav/git-spice/blob/8cc330f5fa24bfbc80fb61d8fab0c03716927eb9/internal/git/commit.go#L101). We'll need a new field on that struct for this option, and in [Repository.Commit](https://github.com/abhinav/git-spice/blob/8cc330f5fa24bfbc80fb61d8fab0c03716927eb9/internal/git/commit.go#L127) we can convert it into a flag passed to Git.

Other minor notes about contributing:

- The project uses [changie](https://changie.dev/) to track unreleased user-facing changes.
- After adding flags, run `make generate` inside the doc/ directory to update the CLI reference.
- Integration tests use [testscript](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript). See [testdata/script/README](https://github.com/abhinav/git-spice/blob/main/testdata/script/README.md) for details. You should be able to adapt any of the existing tests to verify this behavior end-to-end.

**Comment by frank-west-iii** [comment]
@ElPicador, just was looking to see if this functionality exists. Want to check on whether or not you're actively working on this PR or not. Cheers.

**Comment by abhinav** [comment]
@frank-west-iii Thanks! That's fair, the mismatch with `git commit` isn't completely intentional.
Long-term, I want to align with regular Git flags where it makes sense.

Background:
I added `-n` for `--no-edit` early during development because I found myself using `gs commit amend --no-edit` quite often and wanted to map it to `gs ca -n`/`gs can` similarly to [graphite CLI](https://graphite.dev/docs/command-reference).
The project didn't have custom shorthands yet, so I'd added the short flag and hard-coded the `can` alias.

Now that custom shorthands exist, the short form for `--no-edit` isn't necessary since I can map `can` to `commit amend --no-edit` just for myself.
But I don't want to make a breaking change like that without warning.

Suggestion:
- Would you mind just doing the long version of `--no-verify` for now?
- I'm going to put up a change that deprecates but does not remove the `-n` short form for `--no-edit`.
  It'll print a warning when the short form is used, and in a release or two I can drop the `-n` short form from there,
  and put it on `--no-verify`.

**Comment by frank-west-iii** [comment]
Great to know the history and direction.

No problem on leaving out the short form when implementing. 🤙

**Comment by frank-west-iii** [comment]
@ElPicador, I went ahead and took care of the commit path here, but didn't resolve the push hook issues. I don't use any push hooks so it wasn't an immediate need for me, but if you want to take a crack at it the commit PR might be a good reference (after any changes are requested).

**Comment by abhinav** [comment]
Thanks for #509, @frank-west-iii. `--no-verify` for commits should be good enough for now.
If anyone wants to take a stab at `--no-verify` for `git push`-ey commands, it should be similar to #509 in implementation.
