### ISSUE TITLE
Prompt color low contrast

### ISSUE THREAD

**Issue by FinchPowers** [abhinav/git-spice#472]
Hi!

First of all, thank you for the tool, it is really great!
Now, I have a usability problem: The prompt colors have very low contrast, at least for me. I suspect this must be a common issue with dark themes. Sharing here and you can determine if that's a "me" thing or a "git-spice thing".

Look at this screenshot. The Title, Body and Draft headlines are barely visible.

![Capture d’écran, le 2024-11-15 à 11 04 19](https://github.com/user-attachments/assets/c5e01334-0599-4ae3-beb2-48345331bc37)

Highlighting them... highlights the problem 🥁 😆 

![Capture d’écran, le 2024-11-15 à 11 04 42](https://github.com/user-attachments/assets/98e42162-09f2-4c44-afd6-f1067c7802d1)

Thanks again for the tool and have a nice day.

**Comment by abhinav** [comment]
Oh, that isn't right or intentional.
Title is expected to be bright green:

<img width="47" alt="image" src="https://github.com/user-attachments/assets/bf5a2d5b-3438-4b29-a1b3-820f7ea693fc">

https://github.com/abhinav/git-spice/blob/a72ce6e24043a147612e5b019256febfe4e4ff27/internal/ui/style.go#L15

Couple things that might help:

- What terminal are you using?
- What's the value of `$TERM`?

**Comment by FinchPowers** [comment]
Thanks for the reply!

Value of `$TERM` is `screen-256color`
Using `iTerm2` on Mac.

If I run `msgcat --color=test`, here is what the colors look like. So green bold looks ok.

<img width="532" alt="Capture d’écran, le 2024-11-15 à 17 20 20" src="https://github.com/user-attachments/assets/300740fb-9dcf-412c-8e49-bfee90f58560">

**Comment by abhinav** [comment]
I'm trying this out on iTerm2 with screen-256color, but it appears normal:

<img width="219" alt="image" src="https://github.com/user-attachments/assets/36a9c2de-8695-432f-b590-2a0ab4a75e7d">
<img width="121" alt="image" src="https://github.com/user-attachments/assets/01287d36-2e81-45a3-b891-58769d231cf2">

<img width="545" alt="image" src="https://github.com/user-attachments/assets/82c60029-5091-4d99-8ad6-51b6dec826f3">

I've also tried this inside screen and tmux with that configuration.

Since I'm unable to reproduce this, would you mind poking around in Settings > Profiles > Colors?
Another thing to try is, check if dropping the "Bold(true)" here changes things:

https://github.com/abhinav/git-spice/blob/2448b7b8742e22d67be4ce28ba3afafe92b0d156/internal/ui/style.go#L15

**Comment by FinchPowers** [comment]
I ran it again and noticed that the title is indeed green, but just when it's the current prompt. Then it turns black. See screenshot. `Body` is the current prompt and green. `Title` is the previous one, and black.

<img width="179" alt="Capture d’écran, le 2024-11-18 à 08 55 46" src="https://github.com/user-attachments/assets/8a89a61d-7a48-48c0-a12f-01d24710c05f">

Also, thanks a lot for caring! On the other hand, if I'm the only one having this issue, we may consider that it's a "me" thing and close it or wait to see if more users have it.

Here is my iTerm color profile, should it help.

<img width="576" alt="Capture d’écran, le 2024-11-18 à 09 01 12" src="https://github.com/user-attachments/assets/09b6b785-b8cf-4e3b-94a6-2a58fa31a900">

**Comment by abhinav** [comment]
Ahh, the previous field. Yes, that's meant to be faded, but not made completely unreadable. 
Here's how it looks for me:
<img width="376" alt="image" src="https://github.com/user-attachments/assets/73271e67-2f01-4f8e-95c3-2434ca4cf465">

I'm happy to tweak the colors there to improve contrast.
This line controls it:

https://github.com/abhinav/git-spice/blob/a72ce6e24043a147612e5b019256febfe4e4ff27/internal/ui/style.go#L17

Would you be open to tweaking that and experimenting locally?
One value that might be better is: `_titleStyle.Faint(true)` — just the regular title style but faint.

It's completely fine if you'd rather not, in which case we can close this PR as a local settings issue.

**Comment by FinchPowers** [comment]
Absolutely! Let me get back to you.

**Comment by FinchPowers** [comment]
Well, as I was getting ready to work on this, I noticed that the contrast issue is gone...
Here is a screen capture of the former screen capture and the current look.

![Capture d’écran, le 2024-11-21 à 21 50 13](https://github.com/user-attachments/assets/63d6b79f-06d3-4a60-8497-fcde8ea5b660)

I had an iTerm update this week, that may have fixed it somehow? Anyway. We can close this. :)
